CREATE schema EMP1;

CREATE TABLE EMPLOYEES
(
EMPLOYEE_ID INT NOT NULL UNIQUE,
FIRST_NAME VARCHAR(15) NOT NULL,
LAST_NAME VARCHAR(15) NOT NULL,
EMAIL VARCHAR(20) NOT NULL,
HIRE_DATE DATE NOT NULL,
SALARY INT NOT NULL,
COMPISSION_PST FLOAT,
MANAGER_ID INT,
DEPARTMENT_ID int
);

DESCRIBE EMPLOYEES; -- IT WILL SHOW THE TABLE

-- RENAME TABLE
ALTER TABLE EMPLOYEES RENAME TO EMPLOYEE_DATA;
ALTER TABLE EMPLOYEE_DATA RENAME TO EMPLOYEES;

-- ADD COLUMN
ALTER TABLE EMPLOYEES ADD COLUMN JOB_ID VARCHAR(45) NOT NULL;

-- ADD COLUMN AFTER SPECIFIC COLUMN
ALTER TABLE EMPLOYEES ADD COLUMN JOB_ID VARCHAR(45) NOT NULL AFTER HIRE_DATE;


-- TO CHANGE DATA TYPE
ALTER TABLE EMPLOYEES MODIFY COLUMN JOB_ID INT NOT NULL;

-- DELETE COLUMN
ALTER TABLE EMLOYEES DROP COLUMN JOB_ID;

DROP TABLE EMPLOYEES;

DROP SCHEMA EMP1;

COMMIT;  -- IT WILL SAVE THE DATA PERMANENTLY



