SELECT * FROM EMPLOYEES;

DESCRIBE EMPLOYEES;

INSERT INTO EMPLOYEES VALUES (100,'Steven','King','SKING','1987-07-17',24000,NULL,NULL,90);

ALTER TABLE EMPLOYEES MODIFY HIRE_DATE VARCHAR(15) NOT NULL;

UPDATE EMPLOYEES SET HIRE_DATE = date_format(HIRE_DATE,'%d-%b-%y');

INSERT INTO EMPLOYEES VALUES(101,'Neena','Kochhar','NKOCHHAR','21-Sep-89',17000,NULL,100,90);
INSERT INTO EMPLOYEES VALUES(1022,'lux','De Han','LDEHAAN','21-Sep-89',17000,NULL,100,90);

UPDATE EMPLOYEES SET EMPLOYEE_ID = 102 WHERE FIRST_NAME = 'lux';
UPDATE EMPLOYEES SET FIRST_NAME = 'lex' Where EMPLOYEE_ID = 102;
UPDATE EMPLOYEES SET LAST_NAME = 'Da Haan' WHERE EMPLOYEE_ID = 102;
UPDATE EMPLOYEES SET SALARY = 17000 WHERE EMPLOYEE_ID = 102;

DELETE FROM EMPLOYEES WHERE EMPLOYEES_ID = 102;

DROP TABLE EMPLOYEES;

TRUNCATE TABLE EMPLOYEES;

SELECT * FROM EMPLOYEES;
